Vast Teal Bat

high

# `LMPVault.redeem()`/`LMPVault.withdraw()` will revert whenever the destination vault is at a loss and is the last destination vault the loop hits into
## Summary

`LMPVault.redeem()`/`LMPVault.withdraw()` will revert due to failing the `noNavDecrease` modifier at the end if the destination vault is at a loss, and that destination vault is the last one in the withdrawal process.

## Vulnerability Detail

When users call `redeem()` or `withdraw()` function, the `_withdraw()` function is invoked. In the `_withdraw()` function, if the current destination vault being iterated over is the last one and it's in a loss situation, in the current implementation, the call will always revert due to the failure of passing the `noNavDecrease` modifier.

Here is the explanation for that occurrence:  

When the final destination vault encountered in the loop has incurred losses, and the preceding vaults have not, for the call not to revert because the nav decreases, we need to make sure that as the assets leave the system, the assets should go down at a same or lower rate than the shares => `info.debtDecrease` <= `info.totalAssetsPulled` must hold true. 

Because the preceding vaults are not at a loss, for the above requirement to be met, it's necessary that:

> The debt amount burned for the last destination vault  (`totalDebtBurn`) in the loop is less than or equal to the    assets pulled (`assetPulled`)  from that vault.

To satisfy that:  `underlying price of the last dest vault at the last debt reporting` *`sharesToBurn`  (=`totalDebtBurn`) <= `sharesToBurn` * `underlying price now` (`assetPulled`)  =>  `underlying price of the last dest vault at the last debt reporting` <= `underlying price now`, **which is false given the conditions**.

From that, we can deduce that when the previous vaults are not at a loss and the destination vault is at a loss is the last destination vault the loop hits into, it will always revert.
If both the preceding vaults and the final destination vault in the loop have suffered losses, "the debt amount burned in the loop  for the last destination vault  (`totalDebtBurn`) is less than or equal to the assets pulled (`assetPulled`)  from that vault", that condition might no longer hold false, depending on other function arguments. Yet, the possibility of a revert remains considerable.

The vulnerability stems from the interplay of underlying valuation changes, and the conditions required for a successful withdrawal.

Here is the coded scenario to demonstrate the vulnerability:

```solidity
    function test_revert_NAV_decreases_poc() public {
        _accessController.grantRole(Roles.SOLVER_ROLE, address(this));
        _accessController.grantRole(Roles.LMP_FEE_SETTER_ROLE, address(this));

        // User is going to deposit 1000 asset
        _asset.mint(address(this), 1000);
        _asset.approve(address(_lmpVault), 1000);
        _lmpVault.deposit(1000, address(this));

        // Deployed 500 asset to DV1
        _underlyerOne.mint(address(this), 500);
        _underlyerOne.approve(address(_lmpVault), 500);
        _lmpVault.rebalance(
            address(_destVaultOne),
            address(_underlyerOne), // tokenIn
            500,
            address(0), // destinationOut, none when sending out baseAsset
            address(_asset), // baseAsset, tokenOut
            500
        );

        // Deploy 500 asset to DV2
        _underlyerTwo.mint(address(this), 500);
        _underlyerTwo.approve(address(_lmpVault), 500);
        _lmpVault.rebalance(
            address(_destVaultTwo),
            address(_underlyerTwo), // tokenIn
            500,
            address(0), // destinationOut, none when sending out baseAsset
            address(_asset), // baseAsset, tokenOut
            500
        );

        // Drop the price of DV2 to 90% of original, so that 500 we transferred out is now only worth 450
        _mockRootPrice(address(_underlyerTwo), 9e17);

        // The call reverts when the user redeems 700 shares because the NAV decreases
        vm.expectRevert();
        uint256 assets = _lmpVault.redeem(700, address(this), address(this));
    }
```
## Impact

Users attempting to redeem shares/withdraw assets from the LMPVault can experience failed transactions and be unable to withdraw their assets. 

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/LMPVault.sol#L488-L489
https://github.com/sherlock-audit/2023-06-tokemak/blob/main/v2-core-audit-2023-07-14/src/vault/libs/LMPDebt.sol#L284-L295

## Tool used

Manual code review.

## Recommendation

If the destination vault is at a loss and it is the last vault in the withdrawal process, the calculation of `maxAssetsToPull`, `sharesToBurn` and `totalDebtBurn` in the `_calcUserWithdrawSharesToBurn()` function in the current implementation can result in incorrect values. Consider modify `maxAssetsToPull` to ensure that it takes into account the underlying price changes and correctly calculates the maximum assets to be pulled from the destination vault:

```solidity
        maxAssetsToPull = maxAssetsToPull.mulDiv(
            currentDvDebtValue,
            cachedDebtBasis,
            Math.Rounding.Up
        );
```